// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *ContainerModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Ctn1 ([][]uint8) (slice)
	if len("ctn-v1") > 8192 {
		return fmt.Errorf("String in field \"ctn-v1\" was too long")
	}
	if err := jw.WriteString(string("ctn-v1")); err != nil {
		return fmt.Errorf("\"ctn-v1\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Ctn1) > 8192 {
		return fmt.Errorf("Slice value in field t.Ctn1 was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Ctn1: %w", err)
	}
	for i, v := range t.Ctn1 {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Ctn1: %w", err)
			}
		}
		if len(v) > 2097152 {
			return fmt.Errorf("Byte array in field v was too long")
		}

		if err := jw.WriteBytes(v); err != nil {
			return fmt.Errorf("v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Ctn1: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ContainerModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ContainerModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("ContainerModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("ContainerModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("ContainerModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("ContainerModel: string too large")
				}
				return fmt.Errorf("ContainerModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("ContainerModel: %w", err)
			}
			switch name {

			// t.Ctn1 ([][]uint8) (slice)
			case "ctn-v1":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Ctn1: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Ctn1: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Ctn1: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([][]uint8, 1)

							{
								bval, err := jr.ReadBytes(2097152)
								if err != nil {
									if errors.Is(err, jsg.ErrLimitExceeded) {
										return fmt.Errorf("item[0]: byte array too large")
									}
									return fmt.Errorf("item[0]: %w", err)
								}
								if len(bval) > 0 {
									item[0] = []uint8(bval)
								}
							}

							t.Ctn1 = append(t.Ctn1, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Ctn1: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Ctn1: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ContainerModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("ContainerModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("ContainerModel: map too large")
			}
		}
	}

	return nil
}
