// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package datamodel

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *ArgsModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{162}); err != nil {
		return err
	}

	// t.Out (datamodel.ResultModel) (struct)
	if len("out") > 8192 {
		return xerrors.Errorf("Value in field \"out\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("out"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("out")); err != nil {
		return err
	}

	if err := t.Out.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Ran (cid.Cid) (struct)
	if len("ran") > 8192 {
		return xerrors.Errorf("Value in field \"ran\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("ran"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("ran")); err != nil {
		return err
	}

	if err := cbg.WriteCid(cw, t.Ran); err != nil {
		return xerrors.Errorf("failed to write cid field t.Ran: %w", err)
	}

	return nil
}

func (t *ArgsModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = ArgsModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("ArgsModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 3)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Out (datamodel.ResultModel) (struct)
		case "out":

			{

				if err := t.Out.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Out: %w", err)
				}

			}
			// t.Ran (cid.Cid) (struct)
		case "ran":

			{

				c, err := cbg.ReadCid(cr)
				if err != nil {
					return xerrors.Errorf("failed to read cid field t.Ran: %w", err)
				}

				t.Ran = c

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
