//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *ArgsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Out (datamodel.ResultModel) (struct)
	if len("out") > 8192 {
		return fmt.Errorf("string in field \"out\" was too long")
	}
	if err := jw.WriteString(string("out")); err != nil {
		return fmt.Errorf("writing string for field \"out\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Out.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Out: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Ran (cid.Cid) (struct)
	if len("ran") > 8192 {
		return fmt.Errorf("string in field \"ran\" was too long")
	}
	if err := jw.WriteString(string("ran")); err != nil {
		return fmt.Errorf("writing string for field \"ran\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Ran); err != nil {
		return fmt.Errorf("writing CID for field t.Ran: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ArgsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ArgsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for ArgsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for ArgsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for ArgsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field ArgsModel: string too large")
				}
				return fmt.Errorf("reading string for field ArgsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field ArgsModel: %w", err)
			}
			switch name {

			// t.Out (datamodel.ResultModel) (struct)
			case "out":

				if err := t.Out.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Out: %w", err)
				}

				// t.Ran (cid.Cid) (struct)
			case "ran":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("reading CID for field t.Ran: %w", err)
					}
					t.Ran = c

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for ArgsModel: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field ArgsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for ArgsModel")
			}
		}
	}

	return nil
}
