// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *AwaitAnyModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.AwaitAny (cid.Cid) (struct)
	if len("await/*") > 8192 {
		return fmt.Errorf("String in field \"await/*\" was too long")
	}
	if err := jw.WriteString(string("await/*")); err != nil {
		return fmt.Errorf("\"await/*\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.AwaitAny); err != nil {
		return fmt.Errorf("t.AwaitAny: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AwaitAnyModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AwaitAnyModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("AwaitAnyModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("AwaitAnyModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("AwaitAnyModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("AwaitAnyModel: string too large")
				}
				return fmt.Errorf("AwaitAnyModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("AwaitAnyModel: %w", err)
			}
			switch name {

			// t.AwaitAny (cid.Cid) (struct)
			case "await/*":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("t.AwaitAny: %w", err)
					}
					t.AwaitAny = c

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("AwaitAnyModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("AwaitAnyModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("AwaitAnyModel: map too large")
			}
		}
	}

	return nil
}
func (t *AwaitOKModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.AwaitOK (cid.Cid) (struct)
	if len("await/ok") > 8192 {
		return fmt.Errorf("String in field \"await/ok\" was too long")
	}
	if err := jw.WriteString(string("await/ok")); err != nil {
		return fmt.Errorf("\"await/ok\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.AwaitOK); err != nil {
		return fmt.Errorf("t.AwaitOK: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AwaitOKModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AwaitOKModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("AwaitOKModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("AwaitOKModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("AwaitOKModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("AwaitOKModel: string too large")
				}
				return fmt.Errorf("AwaitOKModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("AwaitOKModel: %w", err)
			}
			switch name {

			// t.AwaitOK (cid.Cid) (struct)
			case "await/ok":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("t.AwaitOK: %w", err)
					}
					t.AwaitOK = c

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("AwaitOKModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("AwaitOKModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("AwaitOKModel: map too large")
			}
		}
	}

	return nil
}
func (t *AwaitErrorModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.AwaitError (cid.Cid) (struct)
	if len("await/error") > 8192 {
		return fmt.Errorf("String in field \"await/error\" was too long")
	}
	if err := jw.WriteString(string("await/error")); err != nil {
		return fmt.Errorf("\"await/error\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.AwaitError); err != nil {
		return fmt.Errorf("t.AwaitError: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AwaitErrorModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AwaitErrorModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("AwaitErrorModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("AwaitErrorModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("AwaitErrorModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("AwaitErrorModel: string too large")
				}
				return fmt.Errorf("AwaitErrorModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("AwaitErrorModel: %w", err)
			}
			switch name {

			// t.AwaitError (cid.Cid) (struct)
			case "await/error":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("t.AwaitError: %w", err)
					}
					t.AwaitError = c

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("AwaitErrorModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("AwaitErrorModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("AwaitErrorModel: map too large")
			}
		}
	}

	return nil
}
