// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	datamodel "github.com/alanshaw/ucantone/ipld/datamodel"
	command "github.com/alanshaw/ucantone/ucan/command"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *TokenPayloadModel1_0_0_rc1) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Aud (did.DID) (struct)
	if len("Aud") > 8192 {
		return fmt.Errorf("String in field \"Aud\" was too long")
	}
	if err := jw.WriteString(string("Aud")); err != nil {
		return fmt.Errorf("\"Aud\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Aud.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Aud: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Cmd (command.Command) (string)
	if len("Cmd") > 8192 {
		return fmt.Errorf("String in field \"Cmd\" was too long")
	}
	if err := jw.WriteString(string("Cmd")); err != nil {
		return fmt.Errorf("\"Cmd\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Cmd) > 8192 {
		return fmt.Errorf("String in field t.Cmd was too long")
	}
	if err := jw.WriteString(string(t.Cmd)); err != nil {
		return fmt.Errorf("t.Cmd: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Exp (uint64) (uint64)
	if len("Exp") > 8192 {
		return fmt.Errorf("String in field \"Exp\" was too long")
	}
	if err := jw.WriteString(string("Exp")); err != nil {
		return fmt.Errorf("\"Exp\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if t.Exp == nil {
		if err := jw.WriteNull(); err != nil {
			return fmt.Errorf("t.Exp: %w", err)
		}
	} else {
		if err := jw.WriteUint64(uint64(*t.Exp)); err != nil {
			return fmt.Errorf("t.Exp: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Iss (did.DID) (struct)
	if len("Iss") > 8192 {
		return fmt.Errorf("String in field \"Iss\" was too long")
	}
	if err := jw.WriteString(string("Iss")); err != nil {
		return fmt.Errorf("\"Iss\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Iss.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Iss: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Meta (datamodel.Map) (struct)
	if len("Meta") > 8192 {
		return fmt.Errorf("String in field \"Meta\" was too long")
	}
	if err := jw.WriteString(string("Meta")); err != nil {
		return fmt.Errorf("\"Meta\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Meta.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Meta: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Nbf (uint64) (uint64)
	if len("Nbf") > 8192 {
		return fmt.Errorf("String in field \"Nbf\" was too long")
	}
	if err := jw.WriteString(string("Nbf")); err != nil {
		return fmt.Errorf("\"Nbf\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if t.Nbf == nil {
		if err := jw.WriteNull(); err != nil {
			return fmt.Errorf("t.Nbf: %w", err)
		}
	} else {
		if err := jw.WriteUint64(uint64(*t.Nbf)); err != nil {
			return fmt.Errorf("t.Nbf: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Nonce ([]uint8) (slice)
	if len("Nonce") > 8192 {
		return fmt.Errorf("String in field \"Nonce\" was too long")
	}
	if err := jw.WriteString(string("Nonce")); err != nil {
		return fmt.Errorf("\"Nonce\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Nonce) > 2097152 {
		return fmt.Errorf("Byte array in field t.Nonce was too long")
	}

	if err := jw.WriteBytes(t.Nonce); err != nil {
		return fmt.Errorf("t.Nonce: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Pol (policy.Policy) (struct)
	if len("Pol") > 8192 {
		return fmt.Errorf("String in field \"Pol\" was too long")
	}
	if err := jw.WriteString(string("Pol")); err != nil {
		return fmt.Errorf("\"Pol\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Pol.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Pol: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Sub (did.DID) (struct)
	if len("Sub") > 8192 {
		return fmt.Errorf("String in field \"Sub\" was too long")
	}
	if err := jw.WriteString(string("Sub")); err != nil {
		return fmt.Errorf("\"Sub\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Sub.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Sub: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *TokenPayloadModel1_0_0_rc1) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = TokenPayloadModel1_0_0_rc1{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("TokenPayloadModel1_0_0_rc1: string too large")
				}
				return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
			}
			switch name {

			// t.Aud (did.DID) (struct)
			case "Aud":

				if err := t.Aud.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Aud: %w", err)
				}

				// t.Cmd (command.Command) (string)
			case "Cmd":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Cmd: string too long")
						}
						return fmt.Errorf("t.Cmd: %w", err)
					}
					t.Cmd = command.Command(sval)
				}

				// t.Exp (uint64) (uint64)
			case "Exp":
				{

					nval, err := jr.ReadNumberAsUint64OrNull()
					if err != nil {
						return fmt.Errorf("t.Exp: %w", err)
					}
					if nval != nil {
						typed := uint64(*nval)
						t.Exp = &typed
					}

				}

				// t.Iss (did.DID) (struct)
			case "Iss":

				if err := t.Iss.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Iss: %w", err)
				}

				// t.Meta (datamodel.Map) (struct)
			case "Meta":

				{
					null, err := jr.PeekNull()
					if err != nil {
						return fmt.Errorf("t.Meta: %w", err)
					}
					if null {
						if err := jr.ReadNull(); err != nil {
							return fmt.Errorf("t.Meta: %w", err)
						}
					} else {
						t.Meta = new(datamodel.Map)
						if err := t.Meta.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling t.Meta pointer: %w", err)
						}
					}
				}

				// t.Nbf (uint64) (uint64)
			case "Nbf":
				{

					nval, err := jr.ReadNumberAsUint64OrNull()
					if err != nil {
						return fmt.Errorf("t.Nbf: %w", err)
					}
					if nval != nil {
						typed := uint64(*nval)
						t.Nbf = &typed
					}

				}

				// t.Nonce ([]uint8) (slice)
			case "Nonce":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Nonce: byte array too large")
						}
						return fmt.Errorf("t.Nonce: %w", err)
					}
					if len(bval) > 0 {
						t.Nonce = []uint8(bval)
					}
				}

				// t.Pol (policy.Policy) (struct)
			case "Pol":

				if err := t.Pol.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Pol: %w", err)
				}

				// t.Sub (did.DID) (struct)
			case "Sub":

				if err := t.Sub.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Sub: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("TokenPayloadModel1_0_0_rc1: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("TokenPayloadModel1_0_0_rc1: map too large")
			}
		}
	}

	return nil
}
func (t *SigPayloadModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Header ([]uint8) (slice)
	if len("Header") > 8192 {
		return fmt.Errorf("String in field \"Header\" was too long")
	}
	if err := jw.WriteString(string("Header")); err != nil {
		return fmt.Errorf("\"Header\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Header) > 2097152 {
		return fmt.Errorf("Byte array in field t.Header was too long")
	}

	if err := jw.WriteBytes(t.Header); err != nil {
		return fmt.Errorf("t.Header: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.TokenPayload1_0_0_rc1 (datamodel.TokenPayloadModel1_0_0_rc1) (struct)
	if len("TokenPayload1_0_0_rc1") > 8192 {
		return fmt.Errorf("String in field \"TokenPayload1_0_0_rc1\" was too long")
	}
	if err := jw.WriteString(string("TokenPayload1_0_0_rc1")); err != nil {
		return fmt.Errorf("\"TokenPayload1_0_0_rc1\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.TokenPayload1_0_0_rc1.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.TokenPayload1_0_0_rc1: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *SigPayloadModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = SigPayloadModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("SigPayloadModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("SigPayloadModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("SigPayloadModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("SigPayloadModel: string too large")
				}
				return fmt.Errorf("SigPayloadModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("SigPayloadModel: %w", err)
			}
			switch name {

			// t.Header ([]uint8) (slice)
			case "Header":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Header: byte array too large")
						}
						return fmt.Errorf("t.Header: %w", err)
					}
					if len(bval) > 0 {
						t.Header = []uint8(bval)
					}
				}

				// t.TokenPayload1_0_0_rc1 (datamodel.TokenPayloadModel1_0_0_rc1) (struct)
			case "TokenPayload1_0_0_rc1":

				{
					null, err := jr.PeekNull()
					if err != nil {
						return fmt.Errorf("t.TokenPayload1_0_0_rc1: %w", err)
					}
					if null {
						if err := jr.ReadNull(); err != nil {
							return fmt.Errorf("t.TokenPayload1_0_0_rc1: %w", err)
						}
					} else {
						t.TokenPayload1_0_0_rc1 = new(TokenPayloadModel1_0_0_rc1)
						if err := t.TokenPayload1_0_0_rc1.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling t.TokenPayload1_0_0_rc1 pointer: %w", err)
						}
					}
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("SigPayloadModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("SigPayloadModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("SigPayloadModel: map too large")
			}
		}
	}

	return nil
}
