// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *FixtureModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Input (typegen.Deferred) (struct)
	if len("input") > 8192 {
		return fmt.Errorf("String in field \"input\" was too long")
	}
	if err := jw.WriteString(string("input")); err != nil {
		return fmt.Errorf("\"input\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Input.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Input: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Name (string) (string)
	if len("name") > 8192 {
		return fmt.Errorf("String in field \"name\" was too long")
	}
	if err := jw.WriteString(string("name")); err != nil {
		return fmt.Errorf("\"name\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Name) > 8192 {
		return fmt.Errorf("String in field t.Name was too long")
	}
	if err := jw.WriteString(string(t.Name)); err != nil {
		return fmt.Errorf("t.Name: %w", err)
	}
	written++
	if t.Output != nil {
		if written > 0 {
			if err := jw.WriteComma(); err != nil {
				return err
			}
		}
	}

	// t.Output (typegen.Deferred) (struct)
	if t.Output != nil {
		if len("output") > 8192 {
			return fmt.Errorf("String in field \"output\" was too long")
		}
		if err := jw.WriteString(string("output")); err != nil {
			return fmt.Errorf("\"output\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if err := t.Output.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("t.Output: %w", err)
		}
		written++
	}
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Selector (string) (string)
	if len("selector") > 8192 {
		return fmt.Errorf("String in field \"selector\" was too long")
	}
	if err := jw.WriteString(string("selector")); err != nil {
		return fmt.Errorf("\"selector\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Selector) > 8192 {
		return fmt.Errorf("String in field t.Selector was too long")
	}
	if err := jw.WriteString(string(t.Selector)); err != nil {
		return fmt.Errorf("t.Selector: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *FixtureModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = FixtureModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("FixtureModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("FixtureModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("FixtureModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("FixtureModel: string too large")
				}
				return fmt.Errorf("FixtureModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("FixtureModel: %w", err)
			}
			switch name {

			// t.Input (typegen.Deferred) (struct)
			case "input":

				if err := t.Input.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("failed to read deferred field: %w", err)
				}

				// t.Name (string) (string)
			case "name":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Name: string too long")
						}
						return fmt.Errorf("t.Name: %w", err)
					}
					t.Name = string(sval)
				}

				// t.Output (typegen.Deferred) (struct)
			case "output":

				t.Output = new(jsg.Deferred)

				if err := t.Output.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("failed to read deferred field: %w", err)
				}

				// t.Selector (string) (string)
			case "selector":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Selector: string too long")
						}
						return fmt.Errorf("t.Selector: %w", err)
					}
					t.Selector = string(sval)
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("FixtureModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("FixtureModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("FixtureModel: map too large")
			}
		}
	}

	return nil
}
func (t *FixturesModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Error ([]datamodel.FixtureModel) (slice)
	if len("fail") > 8192 {
		return fmt.Errorf("String in field \"fail\" was too long")
	}
	if err := jw.WriteString(string("fail")); err != nil {
		return fmt.Errorf("\"fail\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Error) > 8192 {
		return fmt.Errorf("Slice value in field t.Error was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Error: %w", err)
	}
	for i, v := range t.Error {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Error: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Error: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Null ([]datamodel.FixtureModel) (slice)
	if len("null") > 8192 {
		return fmt.Errorf("String in field \"null\" was too long")
	}
	if err := jw.WriteString(string("null")); err != nil {
		return fmt.Errorf("\"null\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Null) > 8192 {
		return fmt.Errorf("Slice value in field t.Null was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Null: %w", err)
	}
	for i, v := range t.Null {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Null: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Null: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Success ([]datamodel.FixtureModel) (slice)
	if len("pass") > 8192 {
		return fmt.Errorf("String in field \"pass\" was too long")
	}
	if err := jw.WriteString(string("pass")); err != nil {
		return fmt.Errorf("\"pass\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Success) > 8192 {
		return fmt.Errorf("Slice value in field t.Success was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Success: %w", err)
	}
	for i, v := range t.Success {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Success: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Success: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *FixturesModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = FixturesModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("FixturesModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("FixturesModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("FixturesModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("FixturesModel: string too large")
				}
				return fmt.Errorf("FixturesModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("FixturesModel: %w", err)
			}
			switch name {

			// t.Error ([]datamodel.FixtureModel) (slice)
			case "fail":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Error: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Error: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Error: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]FixtureModel, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Error = append(t.Error, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Error: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Error: slice too large")
							}
						}
					}

				}

				// t.Null ([]datamodel.FixtureModel) (slice)
			case "null":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Null: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Null: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Null: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]FixtureModel, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Null = append(t.Null, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Null: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Null: slice too large")
							}
						}
					}

				}

				// t.Success ([]datamodel.FixtureModel) (slice)
			case "pass":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Success: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Success: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Success: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]FixtureModel, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Success = append(t.Success, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Success: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Success: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("FixturesModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("FixturesModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("FixturesModel: map too large")
			}
		}
	}

	return nil
}
