//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *ParseErrorModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Column (int64) (int64)
	if len("column") > 8192 {
		return fmt.Errorf("string in field \"column\" was too long")
	}
	if err := jw.WriteString(string("column")); err != nil {
		return fmt.Errorf("writing string for field \"column\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Column)); err != nil {
		return fmt.Errorf("writing int64 for field t.Column: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Message (string) (string)
	if len("message") > 8192 {
		return fmt.Errorf("string in field \"message\" was too long")
	}
	if err := jw.WriteString(string("message")); err != nil {
		return fmt.Errorf("writing string for field \"message\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Message) > 8192 {
		return fmt.Errorf("string in field t.Message was too long")
	}
	if err := jw.WriteString(string(t.Message)); err != nil {
		return fmt.Errorf("writing string for field t.Message: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Name (string) (string)
	if len("name") > 8192 {
		return fmt.Errorf("string in field \"name\" was too long")
	}
	if err := jw.WriteString(string("name")); err != nil {
		return fmt.Errorf("writing string for field \"name\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Name) > 8192 {
		return fmt.Errorf("string in field t.Name was too long")
	}
	if err := jw.WriteString(string(t.Name)); err != nil {
		return fmt.Errorf("writing string for field t.Name: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Source (string) (string)
	if len("source") > 8192 {
		return fmt.Errorf("string in field \"source\" was too long")
	}
	if err := jw.WriteString(string("source")); err != nil {
		return fmt.Errorf("writing string for field \"source\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Source) > 8192 {
		return fmt.Errorf("string in field t.Source was too long")
	}
	if err := jw.WriteString(string(t.Source)); err != nil {
		return fmt.Errorf("writing string for field t.Source: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Token (string) (string)
	if len("token") > 8192 {
		return fmt.Errorf("string in field \"token\" was too long")
	}
	if err := jw.WriteString(string("token")); err != nil {
		return fmt.Errorf("writing string for field \"token\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Token) > 8192 {
		return fmt.Errorf("string in field t.Token was too long")
	}
	if err := jw.WriteString(string(t.Token)); err != nil {
		return fmt.Errorf("writing string for field t.Token: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ParseErrorModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ParseErrorModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for ParseErrorModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for ParseErrorModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for ParseErrorModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field ParseErrorModel: string too large")
				}
				return fmt.Errorf("reading string for field ParseErrorModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field ParseErrorModel: %w", err)
			}
			switch name {

			// t.Column (int64) (int64)
			case "column":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.Column: %w", err)
					}
					t.Column = int64(nval)

				}

				// t.Message (string) (string)
			case "message":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Message: string too long")
						}
						return fmt.Errorf("reading string for field t.Message: %w", err)
					}
					t.Message = string(sval)
				}

				// t.Name (string) (string)
			case "name":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Name: string too long")
						}
						return fmt.Errorf("reading string for field t.Name: %w", err)
					}
					t.Name = string(sval)
				}

				// t.Source (string) (string)
			case "source":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Source: string too long")
						}
						return fmt.Errorf("reading string for field t.Source: %w", err)
					}
					t.Source = string(sval)
				}

				// t.Token (string) (string)
			case "token":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Token: string too long")
						}
						return fmt.Errorf("reading string for field t.Token: %w", err)
					}
					t.Token = string(sval)
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for ParseErrorModel: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field ParseErrorModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for ParseErrorModel")
			}
		}
	}

	return nil
}
func (t *ResolutionErrorModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.At ([]string) (slice)
	if len("at") > 8192 {
		return fmt.Errorf("string in field \"at\" was too long")
	}
	if err := jw.WriteString(string("at")); err != nil {
		return fmt.Errorf("writing string for field \"at\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.At) > 8192 {
		return fmt.Errorf("slice value in field t.At was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.At: %w", err)
	}
	for i, v := range t.At {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.At: %w", err)
			}
		}
		if len(v) > 8192 {
			return fmt.Errorf("string in field v was too long")
		}
		if err := jw.WriteString(string(v)); err != nil {
			return fmt.Errorf("writing string for field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.At: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Message (string) (string)
	if len("message") > 8192 {
		return fmt.Errorf("string in field \"message\" was too long")
	}
	if err := jw.WriteString(string("message")); err != nil {
		return fmt.Errorf("writing string for field \"message\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Message) > 8192 {
		return fmt.Errorf("string in field t.Message was too long")
	}
	if err := jw.WriteString(string(t.Message)); err != nil {
		return fmt.Errorf("writing string for field t.Message: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Name (string) (string)
	if len("name") > 8192 {
		return fmt.Errorf("string in field \"name\" was too long")
	}
	if err := jw.WriteString(string("name")); err != nil {
		return fmt.Errorf("writing string for field \"name\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Name) > 8192 {
		return fmt.Errorf("string in field t.Name was too long")
	}
	if err := jw.WriteString(string(t.Name)); err != nil {
		return fmt.Errorf("writing string for field t.Name: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ResolutionErrorModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ResolutionErrorModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for ResolutionErrorModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for ResolutionErrorModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for ResolutionErrorModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field ResolutionErrorModel: string too large")
				}
				return fmt.Errorf("reading string for field ResolutionErrorModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field ResolutionErrorModel: %w", err)
			}
			switch name {

			// t.At ([]string) (slice)
			case "at":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.At: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.At: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.At: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]string, 1)
							{
								sval, err := jr.ReadString(8192)
								if err != nil {
									if errors.Is(err, jsg.ErrLimitExceeded) {
										return fmt.Errorf("reading string for field item[0]: string too long")
									}
									return fmt.Errorf("reading string for field item[0]: %w", err)
								}
								item[0] = string(sval)
							}
							t.At = append(t.At, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.At: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.At: slice too large")
							}
						}
					}

				}

				// t.Message (string) (string)
			case "message":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Message: string too long")
						}
						return fmt.Errorf("reading string for field t.Message: %w", err)
					}
					t.Message = string(sval)
				}

				// t.Name (string) (string)
			case "name":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Name: string too long")
						}
						return fmt.Errorf("reading string for field t.Name: %w", err)
					}
					t.Name = string(sval)
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for ResolutionErrorModel: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field ResolutionErrorModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for ResolutionErrorModel")
			}
		}
	}

	return nil
}
